### ISSUE TITLE
Cannot install sqlite3 for this lab

### ISSUE THREAD

**Issue by reduviidae** [learn-co-curriculum/writing-migrations#14]
I get this error when running bundle install, and cannot complete this lab:

"An error occurred while installing sqlite3 (1.3.13), and Bundler cannot
continue.
Make sure that `gem install sqlite3 -v '1.3.13' --source 'https://rubygems.org/'`
succeeds before bundling."

I tried running `gem install sqlite3 -v '1.3.13' --source 'https://rubygems.org/'` which did not help. 

I also googled the issue and tried a suggested solution of putting sqlite3 in the gem file this way:

"group :development, :test do 
  gem 'sqlite3'
end"

Unfortunately this didn't resolve the issue either.

**Comment by drakeltheryuujin** [comment]
Hi @reduviidae,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

You can consult the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

Otherwise, If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
